import { app, dialog, shell } from 'electron';
import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { appendFileSync, existsSync, mkdirSync, readdirSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path'; import { EventEmitter } from 'node:events';
import { getSettings, saveSettings } from './storage.js'; import type { LocalAISettings, LocalAIStatus, Message } from './types.js';
export type LocalStreamEvent={type:'delta';text:string}|{type:'done';truncated:boolean;coding:boolean;finishReason?:string}|{type:'error';message:string};
class LocalLlmManager extends EventEmitter{
 private child:ChildProcessWithoutNullStreams|null=null;private expectedStop=false;private lines:string[]=[];private stdout:string[]=[];private stderr:string[]=[];private sessionLog='';private status:LocalAIStatus={state:'stopped',message:'Not Loaded'};
 initialize(){const latest=readdirSync(this.dir()).filter(f=>f.startsWith('crash-')&&f.endsWith('.log')).map(f=>({f,t:statSync(path.join(this.dir(),f)).mtimeMs})).sort((a,b)=>b.t-a.t)[0];if(latest)this.status={...this.status,previousCrashLog:path.join(this.dir(),latest.f)}}getStatus(){return this.status}getLogs(){return this.lines.join('\n')}private dir(){const d=path.join(app.getPath('userData'),'logs','local-ai');mkdirSync(d,{recursive:true});return d}private stamp(){return new Date().toISOString().replace(/[:.]/g,'-')}
 private log(message:string,kind:'Ariel'|'stdout'|'stderr'='Ariel'){const line=`[${new Date().toLocaleTimeString()}] [${kind}] ${message}`;this.lines.push(line);if(this.lines.length>3000)this.lines.shift();if(this.sessionLog)appendFileSync(this.sessionLog,line+'\n','utf8');this.emit('log',line)}private setStatus(status:LocalAIStatus){this.status=status;this.emit('status',status)}
 private rotate(){for(const prefix of ['local-ai-','crash-']){const files=readdirSync(this.dir()).filter(f=>f.startsWith(prefix)&&f.endsWith('.log')).map(f=>({f,t:statSync(path.join(this.dir(),f)).mtimeMs})).sort((a,b)=>b.t-a.t);for(const old of files.slice(10))unlinkSync(path.join(this.dir(),old.f))}}
 async selectExecutable(){const r=await dialog.showOpenDialog({title:'Select KoboldCpp executable',properties:['openFile'],filters:[{name:'Windows executable',extensions:['exe']}]});if(r.canceled)return null;const selected=r.filePaths[0];saveSettings({localAI:{...getSettings().localAI,executablePath:selected}});return selected}
 async selectModel(){const r=await dialog.showOpenDialog({title:'Select GGUF model',properties:['openFile'],filters:[{name:'GGUF model',extensions:['gguf']}]});if(r.canceled)return null;const selected=r.filePaths[0];saveSettings({localAI:{...getSettings().localAI,modelPath:selected}});return{path:selected,size:statSync(selected).size}}
 private validate(c:LocalAISettings){if(!c.executablePath||!existsSync(c.executablePath)||path.extname(c.executablePath).toLowerCase()!=='.exe')throw new Error('Select a valid KoboldCpp .exe first.');if(!c.modelPath||!existsSync(c.modelPath)||path.extname(c.modelPath).toLowerCase()!=='.gguf')throw new Error('Select a valid GGUF model first.');if(c.port<1024||c.port>65535)throw new Error('Port must be between 1024 and 65535.')}
 async start(){if(this.child)throw new Error('Ariel already has a Local AI process running.');const c=getSettings().localAI;this.validate(c);this.expectedStop=false;this.lines=[];this.stdout=[];this.stderr=[];this.sessionLog=path.join(this.dir(),`local-ai-${this.stamp()}.log`);writeFileSync(this.sessionLog,'','utf8');const oldCpuBuild=/old[-_ ]?pc/i.test(path.basename(c.executablePath));const args=['--model',c.modelPath,'--port',String(c.port),'--host','127.0.0.1','--contextsize',String(c.contextSize),'--gpulayers',String(c.gpuLayers),'--usevulkan',...(oldCpuBuild?['--noavx2']:[]),'--skiplauncher'];this.log('Ariel Local AI starting');this.log(`Executable: ${c.executablePath}`);this.log(`Old CPU compatibility: ${oldCpuBuild?'enabled (old-PC executable detected)':'not forced'}`);this.log(`Model: ${c.modelPath}`);this.log(`Context=${c.contextSize}; GPU Layers=${c.gpuLayers}; Normal=${c.normalMaxOutput}; Code=${c.codeMaxOutput}`);this.log(`CLI Arguments: ${args.map(a=>a.includes(' ')?`"${a}"`:a).join(' ')}`);this.setStatus({state:'starting',message:'Starting Local Model…',modelFilename:path.basename(c.modelPath),modelSize:statSync(c.modelPath).size,backend:oldCpuBuild?'Vulkan (Old CPU)':'Vulkan',startedAt:Date.now()});
  try{this.child=spawn(c.executablePath,args,{windowsHide:true,stdio:['pipe','pipe','pipe']})}catch(e){return this.fail(e)}const child=this.child!;this.setStatus({...this.status,pid:child.pid});this.log(`KoboldCpp process started (PID ${child.pid})`);child.stdout.on('data',x=>this.capture(String(x),'stdout'));child.stderr.on('data',x=>this.capture(String(x),'stderr'));child.on('error',e=>this.fail(e));child.on('exit',(code,signal)=>this.exited(code,signal));const began=Date.now();while(Date.now()-began<180000&&this.child===child){try{const r=await fetch(`http://127.0.0.1:${c.port}/v1/models`,{signal:AbortSignal.timeout(1500)});if(r.ok){const readyAt=Date.now();this.log(`API ready on port ${c.port}; startup ${readyAt-began}ms`);this.setStatus({...this.status,state:'ready',message:'Ready',readyAt});this.rotate();return this.status}}catch{}await new Promise(r=>setTimeout(r,1000))}if(this.child===child){await this.stop();return this.fail(new Error('Model startup timed out after 180 seconds.'))}return this.status}
 private capture(text:string,kind:'stdout'|'stderr'){for(const raw of text.split(/\r?\n/)){const line=raw.trimEnd();if(!line)continue;const target=kind==='stdout'?this.stdout:this.stderr;target.push(line);if(target.length>500)target.shift();this.log(line,kind)}}
 private fail(error:unknown){const message=error instanceof Error?error.message:String(error);this.log(`Startup failure: ${message}`,'stderr');const crashLog=this.crash('Startup failure');this.child=null;this.setStatus({...this.status,state:'error',message:`Local AI failed to start: ${message}`,crashLog});return this.status}
 private exited(code:number|null,signal:NodeJS.Signals|null){const unexpected=!this.expectedStop;this.log(`Process exited; code=${code}; signal=${signal||'none'}`);this.child=null;if(unexpected){const crashLog=this.crash('Unexpected process exit',code,signal);this.setStatus({...this.status,state:'crashed',message:'Local GGUF stopped unexpectedly.',crashLog})}else this.setStatus({state:'stopped',message:'Not Loaded'});this.expectedStop=false}
 private crash(reason:string,code?:number|null,signal?:NodeJS.Signals|null){const c=getSettings().localAI,file=path.join(this.dir(),`crash-${this.stamp()}.log`);writeFileSync(file,['==================================================','ARIEL LOCAL AI CRASH REPORT','==================================================',`Timestamp: ${new Date().toISOString()}`,`Ariel Version: ${app.getVersion()}`,`Platform: ${process.platform} ${process.arch}`,`Reason: ${reason}`,`Executable: ${c.executablePath}`,`Model: ${c.modelPath}`,`Port: ${c.port}`,`Context Size: ${c.contextSize}`,`GPU Layers: ${c.gpuLayers}`,`Normal Max Output: ${c.normalMaxOutput}`,`Code Max Output: ${c.codeMaxOutput}`,`PID: ${this.status.pid||'n/a'}`,`Exit Code: ${code??'n/a'}`,`Signal: ${signal||'n/a'}`,`Last State: ${this.status.state}`,'','Recent stdout:',...this.stdout.slice(-100),'','Recent stderr:',...this.stderr.slice(-100),'','Recent events:',...this.lines.slice(-200)].join('\n'),'utf8');this.rotate();return file}
 async stop(){if(!this.child){this.setStatus({state:'stopped',message:'Not Loaded'});return}this.expectedStop=true;const pid=this.child.pid;this.log(`Unloading Ariel-owned process PID ${pid}`);if(process.platform==='win32'&&pid)spawn('taskkill',['/pid',String(pid),'/t','/f'],{windowsHide:true});else this.child.kill('SIGTERM')}
 clearLogs(){this.lines=[];this.emit('logs-cleared')}async openLogFolder(){await shell.openPath(this.dir())}async exportLogs(){const r=await dialog.showSaveDialog({title:'Save Local AI Logs',defaultPath:`ariel-local-ai-${this.stamp()}.log`,filters:[{name:'Log file',extensions:['log','txt']}]});if(!r.canceled&&r.filePath)writeFileSync(r.filePath,this.getLogs(),'utf8')}
 isCoding(messages:Message[],continuation=false){if(continuation)return Boolean(messages.at(-1)?.coding);const text=[...messages].reverse().find(m=>m.role==='user')?.content||'';return /\b(write|generate|implement|create|fix|debug|compile|refactor|continue)\b/i.test(text)&&/\b(code|function|class|method|script|api client|component|java(?:script)?|typescript|python|rust|c\+\+|c#|react|electron|node)\b|```/i.test(text)}
 async stream(messages:Message[],send:(e:LocalStreamEvent)=>void,continuation=false){if(this.status.state!=='ready'){send({type:'error',message:'Load the local model first. It cannot answer telepathically. Yet.'});return}const c=getSettings().localAI,coding=this.isCoding(messages,continuation),desired=coding?c.codeMaxOutput:c.normalMaxOutput,system='You are Ariel, a playful, witty, casual and genuinely helpful female assistant. Avoid corporate stiffness. Be precise for technical work.',instruction=continuation?(coding?'Continue exactly where the previous code stopped. Do not repeat code. Preserve language, formatting, indentation and finish incomplete structures.':'Continue exactly where your previous response stopped. Do not repeat content already written.') :'',apiMessages=[{role:'system',content:system},...messages.map(m=>({role:m.role,content:m.content})),...(instruction?[{role:'system',content:instruction}]:[])],promptTokens=Math.ceil(apiMessages.reduce((n,m)=>n+m.content.length,0)/3.5)+apiMessages.length*4,safety=Math.max(64,Math.floor(c.contextSize*.05)),effective=Math.max(1,Math.min(desired,c.contextSize-promptTokens-safety));this.log(`Request: ${coding?'coding':'normal'}; desired=${desired}; prompt≈${promptTokens}; effective max_tokens=${effective}`);if(effective<32){send({type:'error',message:'This chat is too close to the local context limit. Start a new chat or increase Context Size.'});return}try{const response=await fetch(`http://127.0.0.1:${c.port}/v1/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'local-model',messages:apiMessages,stream:true,max_tokens:effective})});if(!response.ok||!response.body)throw new Error(`Local API ${response.status}: ${(await response.text()).slice(0,200)}`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',finishReason:string|undefined;while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.startsWith('data:'))continue;const data=line.slice(5).trim();if(!data||data==='[DONE]')continue;try{const choice=JSON.parse(data).choices?.[0],text=choice?.delta?.content??choice?.text;if(text)send({type:'delta',text});if(choice?.finish_reason)finishReason=choice.finish_reason}catch(e){this.log(`Malformed stream event: ${String(e)}`,'stderr')}}}const truncated=finishReason==='length';this.log(`Generation completed; finish_reason=${finishReason||'unknown'}; truncated=${truncated}`);send({type:'done',truncated,coding,finishReason})}catch(e){const message=e instanceof Error?e.message:String(e);this.log(`Generation failure: ${message}`,'stderr');send({type:'error',message:`Local AI connection failed: ${message}`})}}
}
export const localLlmManager=new LocalLlmManager();
