import Store from 'electron-store';
import { safeStorage } from 'electron';
import type { AppData, Conversation, LocalAISettings, Memory, Settings } from './types.js';
export const localDefaults:LocalAISettings={executablePath:'',modelPath:'',contextSize:2048,gpuLayers:-1,normalMaxOutput:384,codeMaxOutput:1024,port:5001};
const defaults:AppData={settings:{theme:'dark',provider:'openrouter',modelMode:'free',customModel:'',localAI:localDefaults},conversations:[],memories:[]};
const store=new Store<AppData>({name:'ariel-data',defaults});
const mask=(key:string)=>key.length<8?'••••••••':`${key.slice(0,6)}••••••••${key.slice(-4)}`;
export function getSettings():Settings{const key=getApiKey(),stored=store.get('settings');return{...stored,provider:stored.provider||'openrouter',localAI:{...localDefaults,...stored.localAI},hasApiKey:Boolean(key),maskedApiKey:key?mask(key):undefined}}
const int=(v:unknown,min:number,max:number,fallback:number)=>Number.isInteger(Number(v))&&Number(v)>=min&&Number(v)<=max?Number(v):fallback;
export function saveSettings(input:Partial<Omit<Settings,'hasApiKey'|'maskedApiKey'>>):Settings{const current=getSettings(),local=input.localAI?{...current.localAI,...input.localAI}:current.localAI;const clean:LocalAISettings={executablePath:typeof local.executablePath==='string'?local.executablePath.slice(0,2048):'',modelPath:typeof local.modelPath==='string'?local.modelPath.slice(0,2048):'',contextSize:int(local.contextSize,256,524288,2048),gpuLayers:int(local.gpuLayers,-1,1000,-1),normalMaxOutput:int(local.normalMaxOutput,64,2048,384),codeMaxOutput:int(local.codeMaxOutput,128,4096,1024),port:int(local.port,1024,65535,5001)};store.set('settings',{theme:input.theme||current.theme,provider:input.provider||current.provider,modelMode:input.modelMode||current.modelMode,customModel:typeof input.customModel==='string'?input.customModel:current.customModel,localAI:clean});return getSettings()}
export function saveApiKey(key:string):Settings{const clean=key.trim();if(!clean||clean.length>500)throw new Error('Invalid API key');if(safeStorage.isEncryptionAvailable()){store.set('apiKeyEncrypted',safeStorage.encryptString(clean).toString('base64'));store.delete('apiKeyPlainFallback')}else store.set('apiKeyPlainFallback',clean);return getSettings()}
export function getApiKey():string{const encrypted=store.get('apiKeyEncrypted');if(encrypted&&safeStorage.isEncryptionAvailable()){try{return safeStorage.decryptString(Buffer.from(encrypted,'base64'))}catch{return''}}return store.get('apiKeyPlainFallback')||''}
export function removeApiKey():Settings{store.delete('apiKeyEncrypted');store.delete('apiKeyPlainFallback');return getSettings()}
export const getConversations=()=>store.get('conversations');export function saveConversation(c:Conversation){const all=getConversations(),i=all.findIndex(x=>x.id===c.id);if(i>=0)all[i]=c;else all.unshift(c);store.set('conversations',all);return c}export function deleteConversation(id:string){store.set('conversations',getConversations().filter(c=>c.id!==id))}
export const getMemories=()=>store.get('memories');export function addMemories(items:string[]){const existing=getMemories();const fresh:Memory[]=items.filter(text=>!existing.some(m=>m.text.toLowerCase()===text.toLowerCase())).slice(0,5).map(text=>({id:crypto.randomUUID(),text,createdAt:Date.now()}));store.set('memories',[...existing,...fresh].slice(-100))}
