import { ArrowLeft, Cpu, Eye, EyeOff, KeyRound, Moon, Sun, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react'; import type { LocalAISettings, LocalAIStatus, Settings } from '../types';
const stopped:LocalAIStatus={state:'stopped',message:'Not Loaded'};const stateIcon={stopped:'⚪',starting:'🟡',ready:'🟢',error:'🔴',crashed:'💥'};
const basename=(value:string)=>value.split(/[\\/]/).pop()||'Not selected';const size=(bytes?:number)=>bytes?`${(bytes/1024/1024/1024).toFixed(2)} GB`:'Unknown';
export default function SettingsPanel({settings,onChange,onClose}:{settings:Settings;onChange:(s:Settings)=>void;onClose:()=>void}){
 const[key,setKey]=useState(''),[editing,setEditing]=useState(!settings.hasApiKey),[show,setShow]=useState(false),[status,setStatus]=useState<LocalAIStatus>(stopped),[logs,setLogs]=useState(''),[logsOpen,setLogsOpen]=useState(false),[actionError,setActionError]=useState('');
 const patch=async(p:Partial<Settings>)=>onChange(await window.ariel.saveSettings(p));const patchLocal=async(p:Partial<LocalAISettings>)=>patch({localAI:{...settings.localAI,...p}});
 useEffect(()=>{void Promise.all([window.ariel.localAI.getStatus(),window.ariel.localAI.getLogs()]).then(([s,l])=>{setStatus(s);setLogs(l)});const offStatus=window.ariel.localAI.onStatus(setStatus),offLog=window.ariel.localAI.onLog(line=>setLogs(v=>v?`${v}\n${line}`:line)),offClear=window.ariel.localAI.onLogsCleared(()=>setLogs(''));return()=>{offStatus();offLog();offClear()}},[]);
 const saveKey=async()=>{if(!key.trim())return;onChange(await window.ariel.saveApiKey(key));setKey('');setEditing(false)};
 const chooseExe=async()=>{const selected=await window.ariel.localAI.selectExecutable();if(selected)onChange({...settings,localAI:{...settings.localAI,executablePath:selected}})};
 const chooseModel=async()=>{const selected=await window.ariel.localAI.selectModel();if(selected)onChange({...settings,localAI:{...settings.localAI,modelPath:selected.path}})};
 const start=async()=>{setActionError('');try{await patch({localAI:settings.localAI});await window.ariel.localAI.start()}catch(e){setActionError(e instanceof Error?e.message:String(e))}};
 return <section className="settings-view"><div className="settings-inner"><button className="back" onClick={onClose}><ArrowLeft/> Back to chat</button><h1>Settings</h1><p className="settings-lead">The useful knobs. No cockpit engineering degree required.</p>
 <div className="setting-section"><div className="section-icon"><Cpu/></div><div className="section-body"><h2>AI Provider</h2><p>Switch providers whenever you like. No restart, no ceremonial chanting.</p><div className="segmented"><button className={settings.provider==='openrouter'?'selected':''} onClick={()=>patch({provider:'openrouter'})}>OpenRouter</button><button className={settings.provider==='local'?'selected':''} onClick={()=>patch({provider:'local'})}>Local GGUF</button></div></div></div>
 {settings.provider==='openrouter'?<div className="setting-section"><div className="section-icon"><KeyRound/></div><div className="section-body"><h2>OpenRouter</h2><p>Your key stays on this device and is encrypted when Windows allows it.</p>{settings.hasApiKey&&!editing?<div className="saved-key"><code>{settings.maskedApiKey}</code><button onClick={()=>setEditing(true)}>Edit</button><button className="danger" onClick={async()=>{onChange(await window.ariel.removeApiKey());setEditing(true)}}><Trash2/> Remove</button></div>:<div className="key-entry"><div className="input-with-icon"><input type={show?'text':'password'} value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-or-…"/><button onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div><button className="primary" onClick={saveKey} disabled={!key.trim()}>Save key</button>{settings.hasApiKey&&<button onClick={()=>setEditing(false)}>Cancel</button>}</div>}<label>AI model</label><div className="segmented"><button className={settings.modelMode==='free'?'selected':''} onClick={()=>patch({modelMode:'free'})}>OpenRouter Free</button><button className={settings.modelMode==='custom'?'selected':''} onClick={()=>patch({modelMode:'custom'})}>Pick your own</button></div>{settings.modelMode==='custom'&&<input className="model-input" value={settings.customModel} onChange={e=>onChange({...settings,customModel:e.target.value})} onBlur={e=>patch({customModel:e.target.value})} placeholder="anthropic/claude-sonnet-4"/>}</div></div>:
 <div className="setting-section"><div className="section-icon"><Cpu/></div><div className="section-body local-ai"><h2>Local AI</h2><p>Ariel launches and owns this KoboldCpp process. Models stay wherever you put them.</p><div className={`local-status ${status.state}`}><strong>{stateIcon[status.state]} {status.message}</strong>{status.pid&&<span>PID {status.pid}</span>}</div>{status.previousCrashLog&&status.state==='stopped'&&<p className="local-warning">Previous Local AI session ended unexpectedly. Crash log saved: {basename(status.previousCrashLog)}</p>}{actionError&&<p className="local-error">{actionError}</p>}
 <label>KoboldCpp executable</label><div className="path-row"><input value={settings.localAI.executablePath} readOnly placeholder="Select koboldcpp.exe"/><button onClick={chooseExe}>Browse</button></div><small>{basename(settings.localAI.executablePath)}</small>
 <label>GGUF Model</label><div className="path-row"><input value={settings.localAI.modelPath} readOnly placeholder="Select a .gguf model"/><button onClick={chooseModel}>Browse</button></div><small>{basename(settings.localAI.modelPath)} · {size(status.modelSize)}</small>
 <div className="local-grid"><label>Context Size<input type="number" min="256" max="524288" value={settings.localAI.contextSize} onChange={e=>onChange({...settings,localAI:{...settings.localAI,contextSize:Number(e.target.value)}})} onBlur={()=>patchLocal({contextSize:settings.localAI.contextSize})}/></label><label>GPU Layers<input type="number" min="-1" max="1000" value={settings.localAI.gpuLayers} onChange={e=>onChange({...settings,localAI:{...settings.localAI,gpuLayers:Number(e.target.value)}})} onBlur={()=>patchLocal({gpuLayers:settings.localAI.gpuLayers})}/></label><label>Normal Max Output<input type="number" min="64" max="2048" value={settings.localAI.normalMaxOutput} onChange={e=>onChange({...settings,localAI:{...settings.localAI,normalMaxOutput:Number(e.target.value)}})} onBlur={()=>patchLocal({normalMaxOutput:settings.localAI.normalMaxOutput})}/></label><label>Code Max Output<input type="number" min="128" max="4096" value={settings.localAI.codeMaxOutput} onChange={e=>onChange({...settings,localAI:{...settings.localAI,codeMaxOutput:Number(e.target.value)}})} onBlur={()=>patchLocal({codeMaxOutput:settings.localAI.codeMaxOutput})}/></label><label>Port<input type="number" min="1024" max="65535" value={settings.localAI.port} onChange={e=>onChange({...settings,localAI:{...settings.localAI,port:Number(e.target.value)}})} onBlur={()=>patchLocal({port:settings.localAI.port})}/></label><label>Backend<input value={status.backend||'Vulkan (Old CPU)'} readOnly/></label></div>
 <div className="local-actions"><button className="primary" disabled={status.state==='starting'||status.state==='ready'} onClick={start}>{status.state==='crashed'?'Restart Model':'Load Model'}</button><button disabled={status.state==='stopped'} onClick={()=>window.ariel.localAI.stop()}>Unload Model</button><button onClick={()=>setLogsOpen(!logsOpen)}>View Logs</button></div>
 {logsOpen&&<div className="logs-panel"><div><strong>Local AI Logs</strong><span><button onClick={()=>window.ariel.localAI.clearLogs()}>Clear</button><button onClick={()=>navigator.clipboard.writeText(logs)}>Copy</button><button onClick={()=>window.ariel.localAI.exportLogs()}>Save As…</button><button onClick={()=>window.ariel.localAI.openLogFolder()}>Open Folder</button></span></div><pre>{logs||'No Local AI activity yet.'}</pre></div>}</div></div>}
 <div className="setting-section"><div className="section-icon">{settings.theme==='dark'?<Moon/>:<Sun/>}</div><div className="section-body"><h2>Appearance</h2><p>Choose your preferred flavor of tasteful glass.</p><div className="segmented theme-choice"><button className={settings.theme==='dark'?'selected':''} onClick={()=>patch({theme:'dark'})}><Moon/> Dark</button><button className={settings.theme==='light'?'selected':''} onClick={()=>patch({theme:'light'})}><Sun/> Light</button></div></div></div></div></section>
}
