import { useEffect,useRef,useState } from 'react';import TitleBar from './components/TitleBar';import Sidebar from './components/Sidebar';import Chat from './components/Chat';import Composer from './components/Composer';import SettingsPanel from './components/SettingsPanel';import type{Conversation,Message,Settings,StreamEvent}from'./types';
const localDefaults={executablePath:'',modelPath:'',contextSize:2048,gpuLayers:-1,normalMaxOutput:384,codeMaxOutput:1024,port:5001};
const defaultSettings:Settings={theme:'dark',provider:'openrouter',modelMode:'free',customModel:'',localAI:localDefaults,hasApiKey:false};
const fresh=():Conversation=>({id:crypto.randomUUID(),title:'New conversation',messages:[],createdAt:Date.now(),updatedAt:Date.now()});
const titleFor=(s:string)=>{const clean=s.replace(/[#*_`]/g,'').trim().split(/\s+/).slice(0,6).join(' ');return clean.length>38?clean.slice(0,38)+'…':clean||'New conversation'};
export default function App(){
 const[settings,setSettings]=useState<Settings>(defaultSettings),[chats,setChats]=useState<Conversation[]>([]),[active,setActive]=useState<Conversation>(fresh),[sidebar,setSidebar]=useState(true),[view,setView]=useState<'chat'|'settings'>('chat'),[loading,setLoading]=useState(false),[startupError,setStartupError]=useState(''),[greetingExiting,setGreetingExiting]=useState(false);const greetingTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(!window.ariel){setStartupError('Ariel’s secure desktop bridge failed to load.');return}void Promise.all([window.ariel.getSettings(),window.ariel.listChats()]).then(([s,c])=>{setSettings(s);setChats(c);if(c[0])setActive(c[0])}).catch(e=>{console.error('[Ariel startup]',e);setStartupError('Local data stumbled during startup. Settings and chats may be unavailable.')})},[]);useEffect(()=>{document.documentElement.dataset.theme=settings.theme},[settings.theme]);
 const persist=async(c:Conversation)=>{await window.ariel.saveChat(c);setChats(prev=>[c,...prev.filter(x=>x.id!==c.id)].sort((a,b)=>b.updatedAt-a.updatedAt))};
 const runStream=(initial:Conversation,assistantId:string,continuation=false)=>{let current=initial;setLoading(true);const requestMessages=continuation?current.messages:current.messages.slice(0,-1);window.ariel.streamChat(crypto.randomUUID(),requestMessages,event=>{if(event.type==='delta'){current={...current,messages:current.messages.map(m=>m.id===assistantId?{...m,content:m.content+event.text}:m)};setActive(current)}else if(event.type==='error'){current={...current,messages:current.messages.map(m=>m.id===assistantId?{...m,content:m.content+(m.content?'\n\n':'')+event.message,truncated:false}:m),updatedAt:Date.now()};setActive(current);setLoading(false);void persist(current)}else finish(event)},continuation);function finish(event:Extract<StreamEvent,{type:'done'}>){current={...current,messages:current.messages.map(m=>m.id===assistantId?{...m,truncated:Boolean(event.truncated),coding:Boolean(event.coding)}:m),updatedAt:Date.now()};setActive(current);setLoading(false);void persist(current)}};
 const sendImmediately=(content:string)=>{const user:Message={id:crypto.randomUUID(),role:'user',content,createdAt:Date.now()},assistant:Message={id:crypto.randomUUID(),role:'assistant',content:'',createdAt:Date.now()};const current={...active,title:active.messages.length?active.title:titleFor(content),messages:[...active.messages,user,assistant],updatedAt:Date.now()};setActive(current);void persist(current);runStream(current,assistant.id)};
 const send=(content:string)=>{if(active.messages.length){sendImmediately(content);return}setGreetingExiting(true);setLoading(true);greetingTimer.current=setTimeout(()=>{setGreetingExiting(false);sendImmediately(content)},380)};
 const continueResponse=()=>{const last=active.messages.at(-1);if(!last||last.role!=='assistant'||!last.truncated)return;const current={...active,messages:active.messages.map(m=>m.id===last.id?{...m,truncated:false}:m)};setActive(current);runStream(current,last.id,true)};
 const resetGreeting=()=>{if(greetingTimer.current)clearTimeout(greetingTimer.current);greetingTimer.current=null;setGreetingExiting(false);setLoading(false)};const newChat=()=>{resetGreeting();setActive(fresh());setView('chat')};const openChat=(c:Conversation)=>{resetGreeting();setActive(c);setView('chat')};const remove=async(id:string)=>{await window.ariel.deleteChat(id);const rest=chats.filter(c=>c.id!==id);setChats(rest);if(active.id===id)setActive(rest[0]||fresh())};
 return <div className="app-shell"><TitleBar toggleSidebar={()=>setSidebar(!sidebar)} openSettings={()=>setView('settings')}/>{startupError&&<div className="startup-error" role="alert">{startupError}</div>}<div className="body"><Sidebar open={sidebar&&view==='chat'} chats={chats} activeId={active.id} onNew={newChat} onOpen={openChat} onDelete={remove}/><div className={`content ${sidebar&&view==='chat'?'sidebar-visible':''}`}>{view==='settings'?<SettingsPanel settings={settings} onChange={setSettings} onClose={()=>setView('chat')}/>:<><Chat messages={active.messages} loading={loading} conversationId={active.id} greetingExiting={greetingExiting} onContinue={continueResponse}/><Composer onSend={send} disabled={loading}/></>}</div></div></div>
}
